/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jasmina_savic_calendarapp_DurationCalculate */

#ifndef _Included_jasmina_savic_calendarapp_DurationCalculate
#define _Included_jasmina_savic_calendarapp_DurationCalculate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jasmina_savic_calendarapp_DurationCalculate
 * Method:    durationCalculate
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_jasmina_savic_calendarapp_DurationCalculate_durationCalculate
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
